DATA_ROOT: /home/jupyter/deepsentinel/data
DL:
  S1_bands:
  - vv
  - vh
  S2_bands:
  - coastal-aerosol
  - blue
  - green
  - red
  - red-edge
  - red-edge-2
  - red-edge-3
  - nir
  - red-edge-4
  - water-vapor
  - cirrus
  - swir1
  - swir2
  - alpha
GEE:
  S1_bands:
  - VV
  - VH
  S2_bands:
  - B1
  - B2
  - B3
  - B4
  - B5
  - B6
  - B7
  - B8
  - B8A
  - B9
  - B11
  - B12
N_workers: 3
azure_path: /home/jupyter/deepsentinel/azure-connectionstring.txt
day_offset: 3
dt_lookup: 30
ee_credentials: /home/jupyter/deepsentinel/ee-deepsentinel.json
gcp_credentials_path: /home/jupyter/deepsentinel/deepsentinel-gcp-key.json
gcp_storage_bucket: deepsentinel
max_date: '2020-07-31'
min_date: '2019-08-01'
mosaic: false
orbit_period: 12
patch_size: 256
resolution: 10
scihub_auth: /home/jupyter/deepsentinel/credentials.json
selfmatch_offset: 6
